fe_ADK_e-Settlement/fe_ADK_e-Settlement/Controllers/ApproverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fe_ADK_e_Settlement.Controllers.Api;
using fe_ADK_e_Settlement.Controllers.Sample;
using fe_ADK_e_Settlement.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace fe_ADK_e_Settlement.Controllers
{
  public class ApproverController : Controller
  {
    public IActionResult UnitBisnis()
    {
      ViewBag.ApproverUnitBisnis = UnitBisnisList;
      return View();
    }

    public IActionResult Adk()
    {
      ViewBag.ApproverAdk = UnitBisnisList;
      return View();
    }


    public IActionResult ViewDetail()
    {
      return View();
    }



    private IList<ViewTableModel> UnitBisnisList
    {
      get
      {
        string json = JsonSample.JSON_UNITBISNIS_APPROVER;
        var result = JsonConvert.DeserializeObject<List<ViewTableModel>>(json);
        return result;
      }
    }
  }
}

fe_ADK_e-Settlement/fe_ADK_e-Settlement/Views/Approver/Adk.cshtml
@{
    ViewData["Title"] = "Unit Bisnis";
}

<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">

        </div>
    </div>
</div>
<div class="card-header">
    <i class="header-icon lnr-license icon-gradient bg-plum-plate"> </i>Memo Unit Bisnis
</div>
<div class="main-card mb-3 card">
    <div class="card-body">
        <table id="todolistDT" class="mb-0 table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Unit Tujuan</th>
                    <th>Unit Input</th>
                    <th>Nama Debitur</th>
                    <th>Inputer Unit</th>
                    <th>Checker Unit</th>
                    <th>Approver Unit</th>
                    <th>Distribusi</th>
                    <th>Inputer ADK</th>
                    <th>Checker ADK</th>
                    <th>Approver ADK</th>
                    <th>Distribusi</th>
                    <th>Inputer SBO</th>
                    <th>Durasi (menit)</th>
                    <th>ETA</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var items in ViewBag.ApproverAdk)
                {
                    <tr>
                        <td scope="row">@items.id</td>
                        <td>@items.unitTujuan</td>
                        <td>@items.unitInput</td>
                        <td>@items.namaDebitur</td>
                        <td>@items.unitBisnis.inputer</td>
                        <td>@items.unitBisnis.checker</td>
                        <td>@items.unitBisnis.approver</td>
                        <td>@items.adk.distribusi</td>
                        <td>@items.adk.inputer</td>
                        <td>@items.adk.checker</td>
                        <td>@items.adk.approver</td>
                        <td>@items.sbo.distribusi</td>
                        <td>@items.sbo.inputer</td>
                        <td>@items.durasi</td>
                        <td>@items.eta</td>
                       @if (items.status == "created")
                        {
                            <td><a class="badge badge-info" style="color:white;"data-toggle="tooltip" data-placement="top" title="" data-original-title="created">@items.status</a></td>
                        }
                        else if (items.status == "approved")
                        {
                            <td> <a class="badge badge-success" style="color:white;"data-toggle="tooltip" data-placement="top" title="" data-original-title="approved">@items.status</a></td>
                        }
                        else if (items.status == "processed")
                        {
                            <td> <a class="badge badge-warning " style="color:white;"data-toggle="tooltip" data-placement="top" title="" data-original-title="processed">@items.status</a></td>
                        }
                        else if (items.status == "rejected")
                        {
                            <td> <a class="badge badge-danger" style="color:white;" data-toggle="tooltip" data-placement="top" title="" data-original-title="rejected">@items.status</a></td>
                        }
                        <td> <a asp-controller="Approver" asp-action="ViewDetail" class="btn btn-lg btn-info active">Detail</a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="~/js/pages/unit-bisnis.js"></script>

fe_ADK_e-Settlement/fe_ADK_e-Settlement/Views/Approver/UnitBisnis.cshtml
@{
    ViewData["Title"] = "Unit Bisnis";
}

<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">

        </div>
    </div>
</div>
<div class="card-header">
    <i class="header-icon lnr-license icon-gradient bg-plum-plate"> </i>Memo Unit Bisnis
</div>
<div class="main-card mb-3 card">
    <div class="card-body">
        <table id="todolistDT" class="mb-0 table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Unit Tujuan</th>
                    <th>Unit Input</th>
                    <th>Nama Debitur</th>
                    <th>Inputer Unit</th>
                    <th>Checker Unit</th>
                    <th>Approver Unit</th>
                    <th>Distribusi</th>
                    <th>Inputer ADK</th>
                    <th>Checker ADK</th>
                    <th>Approver ADK</th>
                    <th>Distribusi</th>
                    <th>Inputer SBO</th>
                    <th>Durasi (menit)</th>
                    <th>ETA</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var items in ViewBag.ApproverUnitBisnis)
                {
                    <tr>
                        <td scope="row">@items.id</td>
                        <td>@items.unitTujuan</td>
                        <td>@items.unitInput</td>
                        <td>@items.namaDebitur</td>
                        <td>@items.unitBisnis.inputer</td>
                        <td>@items.unitBisnis.checker</td>
                        <td>@items.unitBisnis.approver</td>
                        <td>@items.adk.distribusi</td>
                        <td>@items.adk.inputer</td>
                        <td>@items.adk.checker</td>
                        <td>@items.adk.approver</td>
                        <td>@items.sbo.distribusi</td>
                        <td>@items.sbo.inputer</td>
                        <td>@items.durasi</td>
                        <td>@items.eta</td>
                       @if (items.status == "created")
                        {
                            <td><a class="badge badge-info" style="color:white;"data-toggle="tooltip" data-placement="top" title="" data-original-title="created">@items.status</a></td>
                        }
                        else if (items.status == "approved")
                        {
                            <td> <a class="badge badge-success" style="color:white;"data-toggle="tooltip" data-placement="top" title="" data-original-title="approved">@items.status</a></td>
                        }
                        else if (items.status == "processed")
                        {
                            <td> <a class="badge badge-warning " style="color:white;"data-toggle="tooltip" data-placement="top" title="" data-original-title="processed">@items.status</a></td>
                        }
                        else if (items.status == "rejected")
                        {
                            <td> <a class="badge badge-danger" style="color:white;" data-toggle="tooltip" data-placement="top" title="" data-original-title="rejected">@items.status</a></td>
                        }
                        <td> <a asp-controller="Approver" asp-action="ViewDetail" class="btn btn-lg btn-info active">Detail</a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

<script src="~/lib/jquery/ext/jquery.min.js"></script>
<script type="text/javascript" src="~/js/pages/unit-bisnis.js"></script>